services:
  - type: web
    name: webgames
    env: python
    plan: free
    region: oregon
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn gamehub.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        value: "django-insecure-h!@s)02w+3l^bbz8s*2%n+wasrjqv++o#u#rn+k-vudy8m&bxe"
      - key: DEBUG
        value: "True"
      - key: ALLOWED_HOSTS
        value: "gamehub.onrender.com,localhost"
    autoDeploy: true
    disk:
      mountPath: /tmp
      sizeGB: 1
    healthCheckPath: "/"
    healthCheckIntervalSeconds: 15
    healthCheckTimeoutSeconds: 5
    healthCheckRetries: 3
